import { Eater } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import { cursive, eater } from "../fonts/fonts";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Testing fonts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center h-screen">
        <div className="flex flex-col gap-3">
          <h1 className="font-bold text-3xl">Testing fonts. 1, 2, 3...</h1>
          <p className={`${eater.className} text-5xl`}>
            Do I look thorny to you?
          </p>
          <p className={`${cursive.className} text-3xl`}>
            I am a dignified font from the olden times
          </p>
        </div>
      </main>
    </div>
  );
}
